db:
  host: "trolley.proxy.rlwy.net"
  port: "24014"
  user: "root"
  database: "railway"
  password: "![tqhylWtcXuIswl0384VAYFZvCp/Nf0WPu671mSvRXoykzfUnWVx6EYoTboHaWzhs]"
   
httpRe:
  appid: "![Qs0e2sc89hfZl+rjjrG0O1mdTw3KdoOnULkCK8Moh5+cEEwdDxSzKs6rfFUGh1HX]"   
  method: "GET"
  url : "https://api.openweathermap.org/data/2.5/weather"   
  units: "metric"
  

     
     
